apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Integration
metadata:
  name: "{{ .Values.appName }}-integration"
spec:
  apiID: {{ .Values.apigatewayv2.apiid }}
  connectionID: {{ .Values.apigatewayv2.vpclinkid }}
  connectionType: VPC_LINK
  integrationType: HTTP_PROXY
  integrationURI: {{ .Values.apigatewayv2.lbarn }}
  integrationMethod: GET
  payloadFormatVersion: "1.0"
  description: "integration for {{ .Values.appName }} LB and VPC link"

---

apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Route
metadata:
  name: "{{ .Values.appName }}-route"
spec:
  apiID: {{ .Values.apigatewayv2.apiid }}
  routeKey: "GET /{{ .Values.appName }}"
  targetRef:
    from:
      name: "{{ .Values.appName }}-integration"