apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
metadata:
  name: {{ .Values.appName }}
  namespace: { { .Release.Namespace } }
  labels:
    {{- include "hello.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    canary:
      canaryService: "{{ .Values.appName }}-canary"
      stableService: "{{ .Values.appName }}-stable"
      maxUnavailable: 0
      maxSurge: "25%"
      steps:
        - setWeight: 25
        - pause: { }
      trafficRouting:
        alb:
          ingress: {{ .Values.appName }}
          servicePort: {{ .Values.service.port }}
  selector:
    matchLabels:
      { { - include "hello.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      annotations: {}
      labels:
        {{- include "hello.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets: []
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector: {}
      affinity: {}
      tolerations: []
