apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: API
metadata:
  name: "{{ .Values.appName }}-http-api"
spec:
  name: "{{ .Values.appName }}-http-api"
  protocolType: HTTP

---

apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Integration
metadata:
  name: "{{ .Values.appName }}-integration"
spec:
  apiRef:
    from:
      name: "{{ .Values.appName }}-http-api"
  connectionID: {{ .Values.apigatewayv2.vpclinkid }}
  connectionType: VPC_LINK
  integrationType: HTTP_PROXY
  integrationURI: {{ .Values.apigatewayv2.lbarn }}
  integrationMethod: GET
  payloadFormatVersion: "1.0"

---

apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Route
metadata:
  name: "{{ .Values.appName }}-route"
spec:
  apiRef:
    from:
      name: "{{ .Values.appName }}-http-api"
  routeKey: "GET /{{ .Values.appName }}"
  targetRef:
    from:
      name: "{{ .Values.appName }}-integration"
