apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Integration
metadata:
  name: "{{ .Values.appName }}-integration"
spec:
  apiID: {{ .Values.apigatewayv2.apiid }}
  connectionID: {{ .Values.apigatewayv2.vpclinkid }}
  connectionType: VPC_LINK
  integrationType: HTTP_PROXY
  integrationURI: {{ .Values.apigatewayv2.lbarn }}
  integrationMethod: GET
  payloadFormatVersion: "1.0"

---

apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Route
metadata:
  name: "{{ .Values.appName }}-route"
spec:
  apiRef:
    from:
      name: {{ .Values.apigatewayv2.apiname }}
  routeKey: "GET /{{ .Values.appName }}"
  targetRef:
    from:
      name: "{{ .Values.appName }}-integration"

---

apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Stage
metadata:
  name: "{{ .Values.appName }}"
spec:
  apiRef:
    from:
      name: {{ .Values.apigatewayv2.apiname }}
  stageName: "$default"
  autoDeploy: true
  description: "auto deployed stage for {{ .Values.appName }}-http-api"