# Default values for hi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: "hi"
replicaCount: 2
image:
  repository: 925676107448.dkr.ecr.ap-northeast-2.amazonaws.com/kcd-cicd-kdyoo-hi-app-repo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "bdaaa3a4380a9da8232bcf328161a4c8cabf4f8e"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
maxSurge: 25%
maxUnavailable: 0%
service:
  type: ClusterIP
  port: 8080
ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: kcd-svc-kdyoo-alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/group.name: kcd-svc-kdyoo-apps
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /hi
    alb.ingress.kubernetes.io/subnets: subnet-01c39c85551a37d5f, subnet-0124a5b3d2ca80aa1
  ingressRule:
    - http:
        paths:
          - path: /hi
            pathType: Prefix
            backend:
              service:
                name: hi
                port:
                  number: 8080
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}

apigatewayv2:
  vpclinkid: uvitga
  lbarn: "arn:aws:elasticloadbalancing:ap-northeast-2:751218278275:listener/app/kcd-svc-kdyoo-alb/abbc49cd08d6be84/d27f0e542932388a"
  apiname: kcd-svc-kdyoo-http-api
  apiid: ky8g5wyric
